version: '2.4'
services:
  ziti-controller:
    image: openziti/quickstart:0.22.5
    env_file:
      - ./default.env
    ports:
      - "1280:1280"
    networks:
      ziti:
        aliases:
          - ziti-edge-controller
    volumes:
      - zFiles:/openziti
    entrypoint:
      - "/openziti/scripts/run-controller.sh"

  ziti-edge-router:
    image: openziti/quickstart:0.22.5
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-edge-router
    ports:
      - "3022:3022"
    networks:
      - ziti
    volumes:
      - zFiles:/openziti
    entrypoint: /bin/bash
    command: "/openziti/scripts/run-edge-router.sh edge"

networks:
  ziti:

volumes:
  zFiles:

